import { Vector2D } from '../../internal.js';

/** @typedef {import('../../typedef.js').AllObjectSetup} AllObjectSetup */

/** @type {Array<AllObjectSetup>} */ let Objects = [
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone1', position: new Vector2D(432, 352) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(496, 384) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone3', position: new Vector2D(464, 352) },
	{ class: 'Rock', name: 'Coal Rock', canvasName: 'coalRock', position: new Vector2D(960, 160) },
	{ class: 'Rock', name: 'Iron Rock', canvasName: 'ironRock', position: new Vector2D(992, 160) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(1024, 160) },
	{ class: 'Rock', name: 'Copper Rock', canvasName: 'copperRock', position: new Vector2D(1056, 160) },
	{ class: 'Rock', name: 'silver Rock', canvasName: 'silverRock', position: new Vector2D(1088, 160) },
	{ class: 'Rock', name: 'Gold Rock', canvasName: 'goldRock', position: new Vector2D(1120, 160) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine1', position: new Vector2D(1840, 192) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2', position: new Vector2D(1808, 288) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2', position: new Vector2D(1872, 672) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2', position: new Vector2D(1904, 864) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine1v2', position: new Vector2D(1808, 736) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2v2', position: new Vector2D(1776, 576) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2v2', position: new Vector2D(1872, 352) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine2v2', position: new Vector2D(1776, 160) },
	{ class: 'Tree', name: 'Tree Pine', canvasName: 'treePine1', position: new Vector2D(1872, 96) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch1', position: new Vector2D(1357, 246) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch2', position: new Vector2D(131, 233) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch1', position: new Vector2D(115, 726) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch1', position: new Vector2D(55, 887) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch2', position: new Vector2D(151, 921) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch1', position: new Vector2D(446, 194) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch2', position: new Vector2D(862, 292) },
	{ class: 'ExtendedProp', name: 'Lamppost', canvasName: 'lamppost', position: new Vector2D(193, 269) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 512) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 480) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 448) },
	{ class: 'ExtendedProp', name: 'stonewall_tl_c_br', canvasName: 'terrain', position: new Vector2D(352, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(384, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(416, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(448, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_t_c_b', canvasName: 'terrain', position: new Vector2D(352, 640) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 672) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 704) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 736) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_td', canvasName: 'terrain', position: new Vector2D(352, 768) },
	{ class: 'ExtendedProp', name: 'stonewall_bl_c_tr', canvasName: 'terrain', position: new Vector2D(352, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(384, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(416, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_r_c_l', canvasName: 'terrain', position: new Vector2D(448, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(480, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(512, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(544, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(576, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(608, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_r_c_l', canvasName: 'terrain', position: new Vector2D(672, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_l_c_r', canvasName: 'terrain', position: new Vector2D(768, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(1024, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(800, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(832, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(864, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(896, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(928, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(960, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(1024, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_r_c_l', canvasName: 'terrain', position: new Vector2D(1056, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_r_c_l', canvasName: 'terrain', position: new Vector2D(1056, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(992, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(960, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(928, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(896, 800) },
	{ class: 'ExtendedProp', name: 'stonewall_l_c_r', canvasName: 'terrain', position: new Vector2D(864, 800) },
	{ class: 'ExtendedProp', name: 'House Test', canvasName: 'HouseTest', position: new Vector2D(512, 512) },
	{ class: 'ExtendedProp', name: 'stonewall_b_c_t', canvasName: 'terrain', position: new Vector2D(352, 544) },
	{ class: 'ExtendedProp', name: 'Planning Table', canvasName: 'planningTable', position: new Vector2D(396, 493) },
	{ class: 'ExtendedProp', name: 'Bush 2', canvasName: 'terrain', position: new Vector2D(-170.5, 275) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(640, 416) },
	{ class: 'ExtendedProp', name: 'stonewall_m_c_lr', canvasName: 'terrain', position: new Vector2D(992, 416) },
	{ class: 'ExtendedProp', name: 'Water Filled Boat', canvasName: 'waterFilledBoat', position: new Vector2D(704, 1952) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch1', position: new Vector2D(768, 1856) },
	{ class: 'Tree', name: 'Tree Birch', canvasName: 'treeBirch2', position: new Vector2D(512, 1888) },
	{ class: 'ExtendedProp', name: 'Bush 1', canvasName: 'terrain', position: new Vector2D(633.5, 1895) },
	{ class: 'ExtendedProp', name: 'Bush 2', canvasName: 'terrain', position: new Vector2D(776.5, 1927) },
	{ class: 'CraftingStation', name: 'Chopping Block', canvasName: 'choppingBlock', position: new Vector2D(800, 672) },
	{ class: 'CraftingStation', name: 'Saw Table', canvasName: 'sawTable', position: new Vector2D(800, 544) },
	{ class: 'CraftingStation', name: 'Stone Smelter', canvasName: 'stoneSmelter', position: new Vector2D(896, 448) },
	{ class: 'CraftingStation', name: 'Anvil', canvasName: 'anvil', position: new Vector2D(800, 448) },
	{ class: 'CraftingStation', name: 'Workbench', canvasName: 'workbench', position: new Vector2D(640, 480) },
	{ class: 'CraftingStation', name: 'Stone Cutter', canvasName: 'stoneCutter', position: new Vector2D(896, 672) },
	{ class: 'ExtendedProp', name: 'Wooden Floor 2x2', canvasName: 'woodenFloor2x2', position: new Vector2D(896, 672) },
	{ class: 'CraftingStation', name: 'Planer Bench', canvasName: 'planerBench', position: new Vector2D(896, 544) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-320, 352) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-209.5, 699) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-210.5, 183) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-416, 256) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-589.5, 444) },
	{ class: 'Rock', name: 'Rock Stone', canvasName: 'rockStone2', position: new Vector2D(-442.5, 638) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(352, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(416, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(480, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(599, 1056) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(480, 1088) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(352, 1184) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(352, 1120) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(544, 1088) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(599, 1088) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(599, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(512, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(448, 1088) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(512, 1184) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(599, 1184) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(599, 1152) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(480, 1184) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(416.5, 1183) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(352, 1056) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(641.5, 991) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(672, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(704, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(736, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(768, 992) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(799.5, 970) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(824.5, 934) },
	{ class: 'Rock', name: 'Tin Rock', canvasName: 'tinRock', position: new Vector2D(832, 896) }
];

export { Objects };